const ADDING_CATEGORY_NAME = "Adding Category Name";
const ADDING_CATEGORY_NAME_SUCCESS = "Successfully Added Category Name";
const ADDING_CATEGORY_NAME_FAILURE = "Failed to Add Category Name";

const GETTING_CATEGORIES = "Getting Categories";
const GETTING_CATEGORIES_SUCCESS = "Successfully Fetched Categories";
const GETTING_CATEGORIES_FAILURE = "Failed to Fetch Categories";

export { ADDING_CATEGORY_NAME, ADDING_CATEGORY_NAME_SUCCESS, ADDING_CATEGORY_NAME_FAILURE, GETTING_CATEGORIES, GETTING_CATEGORIES_SUCCESS, GETTING_CATEGORIES_FAILURE };